name = "2020realtors"
main = "src/worker.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "2020realtors"

[env.staging]
name = "2020realtors-staging"

[[d1_databases]]
binding = "DB"
database_name = "realtors_db"
database_id = "your-database-id-here"

[vars]
ENVIRONMENT = "production"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[[kv_namespaces]]
binding = "CACHE"
id = "3a2b9bbc270a4f9097abb1402addc978"
preview_id = "3a2b9bbc270a4f9097abb1402addc978"

[assets]
directory = "./dist"
binding = "ASSETS"

# IDX Broker API Configuration
# Set these as secrets using: wrangler secret put <SECRET_NAME>
# IDX_API_KEY = "your-idx-api-key"
# IDX_PARTNER_KEY = "your-idx-partner-key" (if needed)
# JWT_SECRET = "your-jwt-secret"
# RESEND_API_KEY = "your-resend-api-key" (optional for emails)