name = "realtors-api-final"
main = "src/worker.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "2020realtors-db"
database_id = "3d785a30-04a7-4156-9e55-55bd5284ccc5"

[[kv_namespaces]]
binding = "CACHE"
id = "3a2b9bbc270a4f9097abb1402addc978"

[vars]
ENVIRONMENT = "production"